language: node_js
node_js:
- "0.10"

before_script:
- pwd
- cd /tmp
- git clone --branch=develop https://github.com/appdevdesigns/appdev-cli.git appdev-cli
- cd appdev-cli
- npm install
- npm link
- ./home/travis/build/appdevdesigns/appdev-client/test/setup/install.sh

script:
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs labels/lang-test.html
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs /tmp/ad-test/assets/appdev/labels/label-test.html
- npm test
 