language: node_js
node_js:
- "0.10"

script:
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs labels/lang-test.html
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs labels/label-test.html
- npm test
 