language: node_js
node_js:
- "0.10"

install:
- npm install
- cd /tmp
- git clone --branch=develop https://github.com/appdevdesigns/appdev-cli.git appdev-cli
- cd appdev-cli
- npm link


script:
- mocha-phantomjs labels/lang-test.html
- mocha-phantomjs labels/label-test.html
- npm test
 