language: node_js
node_js:
- "0.10"

before_script:
- pwd
- npm install -g  mocha-phantomjs phantomjs sails
- cd /tmp
- git clone --branch=develop https://github.com/appdevdesigns/appdev-cli.git appdev-cli
- cd appdev-cli
- npm install
- npm link
- cd /tmp
- /home/travis/build/appdevdesigns/appdev-client/test/setup/install.sh

script:
- pwd
- ls -lt /tmp/ad-test/
- ls -lt /tmp/ad-test/node_modules/
- cd /home/travis/build/appdevdesigns/appdev-client/
- mocha-phantomjs /home/travis/build/appdevdesigns/appdev-client/labels/lang-test.html
- mocha-phantomjs /tmp/ad-test/assets/appdev/labels/label-test.html
- npm test
 